### ISSUE TITLE
PSP loader raises UnboundLocalError if channel input is not a list

### ISSUE THREAD

**Issue by Christian-Palmroos** [serpentine-h2020/SEPpy#16]
The error arises in the function calc_av_en_flux_PSP_EPIHI in line 420, due to the variable `en_str` that is defined in line 392, inside an if clause. If the statement in line 392 is evaluated as `False`, then `en_str` is never defined and this raises the error later after the `else` bloack that starts in line 418.

**Comment by jgieseler** [comment]
[Released in version 0.1.4](https://github.com/serpentine-h2020/SEPpy/releases/tag/v0.1.4) ([PyPI](https://pypi.org/project/seppy/0.1.4/))
