### ISSUE TITLE
Fix get_channel_energy_values for SOHO/EPHIN electrons

### ISSUE THREAD

**Issue by jgieseler** [serpentine-h2020/SEPpy#49]
[`get_channel_energy_values()`](https://github.com/serpentine-h2020/SEPpy/blob/2ff9cb844343d7f0d00cb248052ab78532c469d2/seppy/tools/__init__.py) is causing problems for SOHO/EPHIN electrons, before and after the change in data product on Oct 4, 2017. The return array has a length of 4 or 5, depending on time. But actually it should be be 3 or 4. The problems lie in
https://github.com/serpentine-h2020/SEPpy/blob/2ff9cb844343d7f0d00cb248052ab78532c469d2/seppy/tools/__init__.py#L2270-L2274
and
https://github.com/serpentine-h2020/SEPpy/blob/2ff9cb844343d7f0d00cb248052ab78532c469d2/seppy/tools/__init__.py#L2335-L2339
First, it's truncated wrongly. Second, after the change of the data product, one channel info changed to `'deactivated bc. of failure mode D'`, which cause that channel to be skipped in the second code example above.

**Comment by jgieseler** [comment]
Has this been fixed with https://github.com/jgieseler/SEPpy/commit/5d9eb6bae7c84e17255d37e8ec8de4b20388defa?

**Comment by Christian-Palmroos** [comment]
The pull request 52 (https://github.com/serpentine-h2020/SEPpy/pull/52) should address this.
